name: mysignal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.0

  # State management
  provider: ^6.0.5

  # Backend
  supabase_flutter: ^2.8.0

  # Image caching & sharing
  cached_network_image: ^3.3.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ffffff"
  image: images/logoApp.png
  android: true
  ios: true
  android_12:
    image: images/logoApp.png
    icon_background_color: "#ffffff"
  android_gravity: center

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logoApp.png"
  adaptive_icon_foreground: "images/logoApp.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - images/logoApp.png
    - images/signal_Images/